### ISSUE TITLE
Indented numbering with bullets

### ISSUE THREAD

**Issue by alvinzxu** [isocrono/documentator#7]
If I have a numbered list and I want to use indented bullets inside the list, it messes up the formatting for the bullets (turns them into numbers). 

e.g. i tried doing this (note the indented bullets are indented by markdowns 2 spaces)
1. LIST 1 ITEM
   - bullet inside list 1 item
2. LIST 2 ITEM
   - bullet inside list 2 item

**Comment by vahe** [comment]
Fixed.
